import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/css/satoshi.css";
import "@/app/css/style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        suppressHydrationWarning={true}
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
